import telebot
from telebot.util import user_link 
from config import TOKEN, DATABASE, USER, PASSWORD, HOST, PORT
import psycopg2

def connectDB():
    con = psycopg2.connect(
    database=DATABASE, 
    user=USER, 
    password=PASSWORD, 
    host=HOST,   
    port=PORT
    )
    return con



def telegramBot(TOKEN):
    bot = telebot.TeleBot(TOKEN)
    @bot.message_handler(commands=['start'])
    def startMessage(message):
        userId = int(message.from_user.id)
        chatId = int(message.chat.id)
        firstName = str(message.from_user.first_name)
        username = str(message.from_user.username)
        date = int(message.date)
        con = connectDB()
        cur = con.cursor()
        cur.execute(
            f"INSERT INTO users (userid,chatid,first_name,username,pidorCount,date) VALUES ({userId}, {chatId}, '{firstName}', '{username}', 1, {date})"
        )
        con.commit() 
        con.close()
        print (userId, chatId, firstName, username,date)

        bot.send_message(message.chat.id, f"{message.from_user.first_name} vot eta huina")


    bot.infinity_polling()

if __name__ == '__main__':
    telegramBot(TOKEN)

    # con = connectDB()
    # cur = con.cursor()  
    # cur.execute(
    #     "INSERT INTO users (userID,first_name,username,chatID,pidorcount,date) VALUES (123, 'sdas', 'asdad', 123, 43, 32432)"
    # )

    
    
    # cur.execute('''CREATE TABLE IF NOT EXISTS users (
    #     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    #     userid BIGINT NOT NULL,
    #     chatid BIGINT NOT NULL,
    #     first_name character(256),
    #     username character(256),
    #     pidorCount INTEGER,
    #     date BIGINT
    #     );''')
    
    # con.commit() 
    # con.close()