import psycopg2

class postgreSQL:
    def __init__(self, database, user, password, host, port):
        self.connection = psycopg2.connect(
        database=database, 
        user=user, 
        password=password, 
        host=host,   
        port=port
        )
        self.cursor = self.connection.cursor()
    def userExists(self, userId, chatId):
        with self.connection:
            self.cursor.execute(
                f"SELECT * FROM users WHERE userid = {userId} AND chatid = {chatId}"
            )
            return self.cursor.fetchone()

    def addUser(self, userId, chatId, firstName, username, date):
        with self.connection:
            return self.cursor.execute(
                f"INSERT INTO users (userid,chatid,first_name,username,pidorCount,date) VALUES ({userId}, {chatId}, '{firstName}', '{username}', 0, {date})"
            )
    def deleteUser(self, id):
        with self.connection:
            return self.cursor.execute(
                f"DELETE FROM users WHERE id={id}"
            )
    def getRegUsers(self, chatId):
        with self.connection:
            self.cursor.execute(
                f"SELECT * FROM users WHERE chatid = {chatId}"
            )
            return self.cursor.fetchall()
    def setPidorCount(self, chatId, userId, pidorCount):
        with self.connection:
            return self.cursor.execute(f"UPDATE users SET pidorCount={pidorCount} WHERE chatId={chatId} AND userId={userId}")


            
    def createTableUsers(self):
        with self.connection:
            self.cursor.execute('''CREATE TABLE IF NOT EXISTS users (
            id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            userid BIGINT NOT NULL,
            chatid BIGINT NOT NULL,
            first_name character(256),
            username character(256),
            pidorCount BIGINT,
            date BIGINT
            );''')

    def close(self):
        self.connection.close()